# 3.1) NumPy & 0-D and 1-D Arrays

- **Num**erical **Py**thon
- NumPy is a core Python library for scientific computing, making it easier and faster (faster because it’s implemented in C and optimized for performance) to work with numbers and large datasets.
- The main feature of NumPy is the ndarray, a powerful, multi-dimensional array that allows us to store data in an organized grid. This is much faster and more memory-efficient than Python’s regular lists, especially when dealing with large amounts of data.
- Beyond just storing data, NumPy includes a wide range of functions to perform complex tasks directly on these arrays, such as:
  - Math and Statistics: It has tools for performing mathematical calculations, statistical analysis, and random number generation.
  - Data Manipulation: We can reshape, sort, and filter arrays easily.
  - Linear Algebra and Fourier Transforms: It supports more advanced operations like matrix multiplication and signal processing.
  - Compatibility with Other Libraries: NumPy is widely used in data science and is the backbone of other libraries like pandas and SciPy.
- 3-D NumPy arrays are used when we work with images/videos.
- To install a module say numpy we can go to CMD -> Navigate to directory where Python.exe file is present -> Run command pip install module_name
- Broadcasting: NumPy supports broadcasting, allowing you to perform operations between arrays of different shapes, which is particularly helpful in handling matrix operations.

### 0-D NumPy Arrays

In [2]:
import numpy as np    # importing numpy library
a = 45  # when we convert fundamental Python types (like int, float, or single strings) to a NumPy array, they become 0-D arrays.
print(a)
print("Type of a:",type(a))
# converting to numpy array of 0-D:
arr_0 = np.array(a)
print("NumPy array:",arr_0)
print(type(arr_0))

45
Type of a: <class 'int'>
NumPy array: 45
<class 'numpy.ndarray'>


In [3]:
# Now to get dimension of arr_0 array we can do:
arr_0.ndim

0

**shape of array:**
- In an n-dimensional NumPy array, the shape is a property that describes the size of each dimension. 
- It tells us how many elements exist along each axis (dimension) of the array. The shape is represented as a tuple, where each value in the tuple corresponds to the number of elements along a particular dimension.
- Example:
  - Shape: () -> This means it has 0 dimensions. Like a single number has no dimensions
  - Shape: (4,) → This means it has 1 dimension with 4 elements along it.
  - Shape: (2, 3) → This means it has 2 dimensions. The first dimension (rows) has 2 elements, and the second dimension (columns) has 3 elements.

In [4]:
# To get shape of arr_0 we can do:
arr_0.shape

()

### 1-D NumPy Arrays

**converting a list to array:**

In [5]:
a = [1, 2, 3, 4]
print(a)
print(type(a))

[1, 2, 3, 4]
<class 'list'>


In [6]:
import numpy as np
arr_11 = np.array(a)
print(arr_11)
arr_11

[1 2 3 4]


array([1, 2, 3, 4])

In [16]:
arr_11.ndim

1

In [15]:
arr_11.shape

(4,)

**converting a tuple to array:**

In [17]:
tup = (1, 2, 5)
arr_12 = np.array(tup)
print(arr_12)
arr_12

[1 2 5]


array([1, 2, 5])

In [18]:
arr_12.ndim

1

In [20]:
arr_12.shape

(3,)

**converting a set to array:**

In [9]:
s = {1, 2, 4, 8}
arr_13 = np.array(s)
arr_13

array({8, 1, 2, 4}, dtype=object)

In [10]:
print(arr_13)

{8, 1, 2, 4}


In [11]:
print(type(arr_13))

<class 'numpy.ndarray'>


In [21]:
# It seems that we have converted set to array successfully. But it is not so, we can see the problem when we check the dimension and shape

In [12]:
arr_13.ndim

0

In [26]:
arr_13.shape

()

- To convert a set to a NumPy array, we need to first convert the set to a list (or another ordered sequence say tuple).
- When we directly pass a set to np.array(), NumPy recognizes the set as a single object rather than iterating over its elements. This results in a 0-D array containing the set itself, rather than an array of its elements.

In [22]:
# correct way:
arr_14 = np.array(list(s))
print(arr_14)

[8 1 2 4]


In [24]:
arr_14.ndim

1

In [25]:
arr_14.shape

(4,)

#### Functions for creating 1D array:

**i. arange():**
- It is same as range() function but arange() gives the value in range as an array. In other words we can say that arange() gives an array-valued version of the built-in Python range function.
- **Syntax:** np.arange(start, end, step)

In [29]:
arr_15 = np.arange(1, 10, 2)
print(arr_15)
arr_15

[1 3 5 7 9]


array([1, 3, 5, 7, 9])

**ii. linspace():**
- The np.linspace() function in NumPy generates an array of evenly spaced values over a specified interval.
- It’s particularly useful when we need a specific number of values within a range, which is common in scientific and mathematical computations.
- Syntax: np.linspace(start, stop, num=50, endpoint=True, retstep=False, dtype=None)
- Example: np.linspace(0,5,6) will break down [0,5] in 6 equal interval so we will get o/p as [0., 1., 2., 3., 4., 5.]
- Interval_size = (end-start)/((num_of_samples i.e. intervals) - 1)

In [32]:
arr_16 = np.linspace(0,5, 6)
arr_16

array([0., 1., 2., 3., 4., 5.])

**iii. zeros():**
- Generates array of zeros
- Syntax: zeros(shape, dtype=float, order='C', *, like=None)
  - shape = tuple (except in 1D we can simply provide value instead of tuple)
  - dtype = float by default

In [33]:
arr_17 = np.zeros((4,))
arr_17

array([0., 0., 0., 0.])

In [35]:
arr_18 = np.zeros(4) # provide value instead of tuple in shape
print(arr_18.ndim)
arr_18

1


array([0., 0., 0., 0.])

In [38]:
arr_19 = np.zeros((4,), dtype =int)
arr_19

array([0, 0, 0, 0])

**iv. ones():**
- Same as zeros() but it gives array of ones

In [40]:
arr_20 = np.ones((3,))
arr_20

array([1., 1., 1.])

**v. random.randint():**
- returns random integer as an array from start(inclusive) to end(exclusive)
- Syntax: np.random.randint(start, end, num_of_samples)
- Note: It is part of numpy module and not of random module else we would have to import random module to use it

In [42]:
# Problem with random modules randint(): Suppose we were to generate 5 random values in the range [1,100) then:-
import random
l = []
for i in range(5):
    l.append(random.randint(1,100))
l

[29, 44, 96, 75, 72]

In [43]:
# Just one line of code for generating five random values in [1,100) using numpy
a = np.random.randint(1,100,5)
a

array([98,  6, 59, 92, 55], dtype=int32)

### Accessing elements/ Extracting the values
1. Accessing a single value through indexing
2. Accessing multiple values based on slicing
3. Accessing multiple values based on indexing
4. Accessing multiple value based on condition

In [44]:
a = np.array([100,120,130,190,200,14,18,26])
print(a)

[100 120 130 190 200  14  18  26]


**1. Accessing a single value through indexing**

In [46]:
# positive indexing
print(a[1])
a[1]

120


np.int64(120)

In [47]:
# negative indexing
print(a[-1])

26


**2. Accessing multiple values based on slicing**

In [48]:
print(a[0:5:2])   # we will get items at index 0,2,4

[100 130 200]


**3. Accessing multiple values based on indexing**
- Syntax: array[list/tuple of indexes]

In [49]:
a[[1,2,4]]

array([120, 130, 200])

In [60]:
print(a[(2, )])

130


In [62]:
print(a[(1,3)])  # it will treat (1,3) as dimension

IndexError: too many indices for array: array is 1-dimensional, but 2 were indexed

**4. Accessing multiple value based on condition**
- Syntax: array[condition]
  - first it will check the condition, the item which satisfies the condition (means which items gives True for the condition), that item will be selected

In [64]:
a = np.array([45,46,47])
a>45   # this gives an array of booleans indicating which item of the array 'a' satisfies the condition

array([False,  True,  True])

In [65]:
# suppose we want to get an array of items that satisfies the condition then we have to do:
a[a>45]

array([46, 47])

### Modifying the values in NumPy

**1. Add single/ multiple value in the array:**
- Syntax: np.append(array, value)

In [66]:
a = np.array([45, 46, 47])
a1 = np.append(a, 100)
print(a1)

[ 45  46  47 100]


In [67]:
# adding multiple values
a = np.array([45, 46, 47])
a1 = np.append(a, [100, 200, 300])   # Here, [100, 200, 300] will not be added as 1-item else it will make the array 2-D
print(a1)

[ 45  46  47 100 200 300]


In [68]:
a = np.array([45, 46, 47])
a1 = np.append(a, (100, 100, 200))
print(a1)

[ 45  46  47 100 100 200]


**2. Replacing a single value in a 1D array:**

In [69]:
a = np.array([45, 46, 47])
a[1] = 100
print(a)

[ 45 100  47]


**3. Replacing multiple values with a single value**

In [73]:
a = np.array([45, 46, 47])
a[[1, 2]] = [100]   # elements at index 1 and 2 will become 100
print(a)

[ 45 100 100]


In [70]:
a = np.array([45, 46, 47])
a[[1, 2]] = 100   # elements at index 1 and 2 will become 100
print(a)

[ 45 100 100]


**4. Replacing multiple values with multiple values**

In [71]:
a = np.array([45, 46, 47])
a[[0,1]] = [100, 102]
print(a)

[100 102  47]


In [74]:
a = np.array([45, 46, 47])
a[[0,1]] = [100, 200, 2]
print(a)

ValueError: shape mismatch: value array of shape (3,) could not be broadcast to indexing result of shape (2,)

**5. Deleting a single value in an array:**
- Syntax: np.delete(array, index_number) - this method returns a new array

In [79]:
a = np.array([45, 46, 47])
a1 = np.delete(a, 0)
print(a1)
a

[46 47]


array([45, 46, 47])

**6. Deleting multiple values in an array:**
- Syntax: np.delete(array, [multiple_indexes])

In [80]:
a = np.array([45, 46, 47])
a1 = np.delete(a, [1,0])
print(a1)
a

[47]


array([45, 46, 47])

**7. Copying arrays:**
- Syntax: array.copy() - creates shallow copy

In [82]:
a = np.array([1, 2, 3])
print(a)
b = a.copy()
print(b)
b[0] = 100
print(b)
a

[1 2 3]
[1 2 3]
[100   2   3]


array([1, 2, 3])

**8. Sorting an array:**

In [83]:
a = np.array([4, 6, 8, 2, 1])
b = np.sort(a)
print(b)
a

[1 2 4 6 8]


array([4, 6, 8, 2, 1])

In [107]:
# sorting when array is a mixture of lowercase alphabets, uppercase alphabets and numbers
arr = np.array([4,6, 8, 2, 1, "a", "A"])
b = np.sort(arr)  # sorting based on Unicode value
b

array(['1', '2', '4', '6', '8', 'A', 'a'], dtype='<U21')

In [108]:
# sorting when array is a mixture of lowercase alphabets, uppercase alphabets and numbers
arr = np.array([4,6, 8, 2, 1, "a", "A", "Abhi", "B"])
b = np.sort(arr)  # sorting based on Unicode value (Here Abhi will come before B)
b

array(['1', '2', '4', '6', '8', 'A', 'Abhi', 'B', 'a'], dtype='<U21')

In [109]:
# sorting when array is a mixture of lowercase alphabets, uppercase alphabets and numbers
arr = np.array([4, 6, 8, 2, 1, 100, 200, "a", "A", "Abhi", "B"])
b = np.sort(arr)  # sorting based on Unicode value (Here 100 will come before 2 and 200 will come before 4 same as Abhi came before B in above example)
b

array(['1', '100', '2', '200', '4', '6', '8', 'A', 'Abhi', 'B', 'a'],
      dtype='<U21')

### Operations

**1. Arithmetic operations:**

In [84]:
a = np.array([1, 2, 3, 4])
print(a)

[1 2 3 4]


In [86]:
b = a+1   # it will add 1 to all items of array a (same task without numpy would require more code i.e. we would require to write loop)
b

array([2, 3, 4, 5])

In [87]:
c = a+0
c

array([1, 2, 3, 4])

In [88]:
d = a**2
d

array([ 1,  4,  9, 16])

In [89]:
print(a+b)   # item at an index of array 'a' gets added to item at same index in 'b'

[3 5 7 9]


In [95]:
# if shape of two arrays is not same and we try to perform Arithmetic operation then we get error:
x = np.array([1, 2, 3])
y = np.array([2, 3])
print(x.shape)
print(y.shape)
print(x+y)

(3,)
(2,)


ValueError: operands could not be broadcast together with shapes (3,) (2,) 

In [96]:
print(a*b)

[ 2  6 12 20]


**2. Comparison Operators:**

In [97]:
a == b   # item at an index of array 'a' gets compared to item at same index in 'b'

array([False, False, False, False])

In [98]:
b>=a

array([ True,  True,  True,  True])

In [99]:
np.array_equal(a,b)  # returns True if all items at corresponding indexes are same in a and b, else it returns False

False

In [100]:
np.array_equal(a,c)

True

**3. Mathematical Operations:**

In [101]:
a = np.array([0, 1, 2, 3, 4])
a

array([0, 1, 2, 3, 4])

In [102]:
np.exp(a)    # returns (e)^items_of_array

array([ 1.        ,  2.71828183,  7.3890561 , 20.08553692, 54.59815003])

In [103]:
np.log(a)   # returns log(eac_items in array)

C:\Users\abhin\AppData\Local\Temp\ipykernel_612\3575311366.py:1: RuntimeWarning: divide by zero encountered in log
  np.log(a)   # returns log(eac_items in array)


array([      -inf, 0.        , 0.69314718, 1.09861229, 1.38629436])

- in above np.log(a) gives warning because we know that log(0) = -Infinity
- If we want to supress the above warning then we can use warnings module simplefilter() which can take the following action:
  - "ignore": Ignore the warning.
  - "error": Turn the warning into an error.
  - "always": Always s|how the warning, even if it's already been shown.
  - "default": Show the warning only the first time it’s triggered.
  - "module": Show the warning once per module.
  - "once": Show the warning only once.

In [104]:
import warnings as w
w.simplefilter("ignore")
np.log(a)

array([      -inf, 0.        , 0.69314718, 1.09861229, 1.38629436])

In [105]:
import warnings as w
w.simplefilter("error")
np.log(a)

RuntimeWarning: divide by zero encountered in log