# 3.2) 2-D NumPy Arrays

- Arrays having rows and columns (i.e. matrix)
- Collection of 1-D arrays is 2-D array and collection of 2-D arrays is 3-D array.

### Creating 2-D array

In [2]:
import numpy as np
l = [[1,2,3],[4,5,6]]   # it is nested list
a = np.array(l)
print(a)
a

[[1 2 3]
 [4 5 6]]


array([[1, 2, 3],
       [4, 5, 6]])

- If suppose we have two lists as: l1=[1,2,3] and l2=[4,5] and want to convert these list to 2-D array then compulsory we have to make both list of same length else we will get error

In [3]:
l1 = [1, 2, 3]
l2 = [4,5]
a = np.array([l1,l2])

ValueError: setting an array element with a sequence. The requested array has an inhomogeneous shape after 1 dimensions. The detected shape was (2,) + inhomogeneous part.

In [4]:
l1 = [1,2,3]
l2 = [4,np.nan,5]
a = np.array([l1,l2])
print(a)   # since we used np.nan we will get 2-D array of float values

[[ 1.  2.  3.]
 [ 4. nan  5.]]


In [6]:
a.ndim

2

In [7]:
a.shape

(2, 3)

In [10]:
c = np.array([1,2,3])
d = np.array([[1,2,3]])
print(c.shape)
d.shape

(3,)


(1, 3)

**np.zeros()**

In [12]:
np.zeros((3,4))

array([[0., 0., 0., 0.],
       [0., 0., 0., 0.],
       [0., 0., 0., 0.]])

In [13]:
np.zeros((3,3), dtype=int)

array([[0, 0, 0],
       [0, 0, 0],
       [0, 0, 0]])

**np.ones()**

In [14]:
np.ones((2,3))

array([[1., 1., 1.],
       [1., 1., 1.]])

- (Q) What if we want create a matrix with all rows and columns filled with a number other than 0 and 1(say 2)?
  - We can create manually
  - Or we can do the following:

In [15]:
np.ones((2,3))+1

array([[2., 2., 2.],
       [2., 2., 2.]])

In [16]:
np.zeros((2,3))+2

array([[2., 2., 2.],
       [2., 2., 2.]])

### Special matrixes

- **Square matrix and rectangular matrix:**
  - Square matrix: A matrix with the same number of rows and columns. Shape is like (n,n)
  - Rectangular matrix: A matrix with a different number of rows and columns. Typically, rectangular matrices are described by their dimensions as 𝑚×𝑛,
where 𝑚≠𝑛

- **Symmetrix and Unsymmetric matrix**
  - Symmetric matrix:
    - A symmetric matrix is a square matrix where the element at position (i,j) is equal to the element at position (j,i).
    - In simpler terms, a symmetric matrix is identical to its transpose (the matrix formed by swapping rows and columns).
    - A symmetric matrix is symmetric with respect to the main diagonal (i.e. diagonal from left to right).
  - Unsymmetric matrix:
    - An unsymmetric matrix does not have the symmetry property. This means there exists at least one element A(i,j) that is not equal to A(j,i).

In [ ]:
# example of symmetric matrix
[[1,2,3],
 [2,4,5],
 [3,5,6]]

# example of unsymmetric matrix
[[1,0,3],
 [2,4,5],
 [3,5,6]]

**Identity Matrix:**
- An identity matrix is a symmetric and square matrix where:
  - The main diagonal has values of 1
  - All other elements (those not on the main diagonal) are 0

In [18]:
# creating an identity matrix in NumPy python:
np.eye(3,3)

array([[1., 0., 0.],
       [0., 1., 0.],
       [0., 0., 1.]])

In [19]:
np.eye(2,2, dtype=int)

array([[1, 0],
       [0, 1]])

In [20]:
np.eye((2,2), dtype=int)

TypeError: 'tuple' object cannot be interpreted as an integer

**Diagonal matrix:**
- A diagonal matrix is a square matrix where all the elements outside the main diagonal are zero.
- Only the elements on the main diagonal (from the top-left to the bottom-right) can have non-zero values.
- For creating a diagonal matrix in Python we use np.diag() method.

In [21]:
# case 1: When we pass 1-D list as the parameter to np.diag()- It creates a diagonal matrix with the list items along main diagonal
np.diag([1,2,3,4])

array([[1, 0, 0, 0],
       [0, 2, 0, 0],
       [0, 0, 3, 0],
       [0, 0, 0, 4]])

In [22]:
# case 2: when we pass 2-D list as the parameter to np.diag()- It creates a 1-D array with the items extracted from the main diagonal of 2-D list
np.diag([[1,2,3],[4,5,6],[10,20,30]])  # array with diagonal elements=[1 5 30]

array([ 1,  5, 30])

### Indexing and slicing

In [23]:
a=np.array([[10,20,50],[30,40,60],[20,80,90]])
print(a)

[[10 20 50]
 [30 40 60]
 [20 80 90]]


In [26]:
# extracting a row:
print(a[1])

[30 40 60]


In [27]:
# extracting one value
a[1][2]

np.int64(60)

In [28]:
print(a[1][2])

60


In [29]:
# negative indexing is also possible
print(a[-3][-1])

50


In [31]:
# slicing:
a[1:3]   # starting from row 1 to 3-1 =2nd row

array([[30, 40, 60],
       [20, 80, 90]])

### Replace/Assign the value

- replacing/assigning a single value:

In [34]:
a[2,2] = 500
a

array([[ 10,  20,  50],
       [ 30,  40,  60],
       [ 20,  80, 500]])

- replacing/assigning a row:

In [35]:
a[1] = [100, 200, 500]
a

array([[ 10,  20,  50],
       [100, 200, 500],
       [ 20,  80, 500]])

### Flattening

- [[1st row elements], [2nd row elements]]  ---- (flattening) ----> [1st row elements, 2nd row elements]
- For this we use np.ravel() method

In [37]:
# converting 2-D array to 1-D array:
a = np.array([[0,1,2],[3,4,5]])
print(a)

b = a.ravel()
print(b)

[[0 1 2]
 [3 4 5]]
[0 1 2 3 4 5]


### Reshaping array
- Changing the shape
- For example if we have an array of shape (6,) then we can reshape it to (1,6) or (2,3) or (3,2) or (6,1)

In [39]:
arr = np.arange(6)
print(arr)
arr.shape

[0 1 2 3 4 5]


(6,)

In [40]:
a1 = arr.reshape(2,3)
a1

array([[0, 1, 2],
       [3, 4, 5]])

In [42]:
arr.reshape(6,1)

array([[0],
       [1],
       [2],
       [3],
       [4],
       [5]])

In [43]:
arr.reshape(1,6)

array([[0, 1, 2, 3, 4, 5]])

- **reshaping 2-D array:**

In [45]:
a = np.array([[0,1,5],[10,5,8]])  # matrix of shape (2,3)
a.shape

(2, 3)

In [46]:
# We can convert it to (1,6), (2,3), (3,2), and (6,1)

In [47]:
a.reshape(1,6)

array([[ 0,  1,  5, 10,  5,  8]])

In [48]:
a.reshape(6,1)

array([[ 0],
       [ 1],
       [ 5],
       [10],
       [ 5],
       [ 8]])

In [50]:
a.reshape(2,3)

array([[ 0,  1,  5],
       [10,  5,  8]])

In [51]:
a.reshape(3,2)

array([[ 0,  1],
       [ 5, 10],
       [ 5,  8]])

- **transpose of a matrix**
  - Interchanging of rows and columns

In [52]:
a = np.array([[1,2,3],[4,5,6]])
a

array([[1, 2, 3],
       [4, 5, 6]])

In [53]:
b = a.T   # transpose of a
b

array([[1, 4],
       [2, 5],
       [3, 6]])

### Sorting
- row-sort vs columns-sort
  - row-sort: sorting row items separately for each row i.e. each row will be sorted separately.
  - column-sort: sorting column items separately for each column i.e. each column will be sorted separately
- **Note:** For column-sort in NumPy we have to provide axis = 0 and for row-sort we provide axis = 1. **These values of axis is reverse in Pandas.**

In [54]:
a = np.array([[5,4,6],[2,8,9],[8,9,10]])
a

array([[ 5,  4,  6],
       [ 2,  8,  9],
       [ 8,  9, 10]])

In [55]:
# sorting along an axis = 1 i.e. row
np.sort(a,axis = 1)

array([[ 4,  5,  6],
       [ 2,  8,  9],
       [ 8,  9, 10]])

In [56]:
# sorting along an axis = 0 i.e. column
np.sort(a,axis = 0)

array([[ 2,  4,  6],
       [ 5,  8,  9],
       [ 8,  9, 10]])

### Mathematical Operations
- Similar to 1-D arrays, shape must be same of 2-D arrays in order to perform mathematical operations between them else we will get ValueError.

In [57]:
a = np.array([[1,2],[3,4],[5,6]])
b = np.array([[40,4],[14,24],[34,44]])
print(a.shape==b.shape)

True


In [58]:
a

array([[1, 2],
       [3, 4],
       [5, 6]])

In [59]:
b

array([[40,  4],
       [14, 24],
       [34, 44]])

In [60]:
a+b   # elements at corresponding indexes will be added (i.e. elementwise addition)

array([[41,  6],
       [17, 28],
       [39, 50]])

In [61]:
a*b   # elements at corresponding indexes will be multiplied (i.e. elementwise multiplication a.k.a dot product of matrix)

array([[ 40,   8],
       [ 42,  96],
       [170, 264]])

In [62]:
# what if shapes are not equal
c = np.array([[40,4,2],[14,24],[34,44]])
a+c

ValueError: setting an array element with a sequence. The requested array has an inhomogeneous shape after 1 dimensions. The detected shape was (3,) + inhomogeneous part.

- **What if we want matrix multiplication but not dot product?**
  - For this we have np.matmul() method

In [63]:
a = np.array([[1,2],[3,4]])
b = np.array([[5,6],[7,8]])
np.matmul(a,b)

array([[19, 22],
       [43, 50]])

### Concatening/Joining multiple 2-D arrays

In [64]:
a = np.array([[1,2],[3,4]])
b = np.array([[5,6],[7,8]])
print(a)
b

[[1 2]
 [3 4]]


array([[5, 6],
       [7, 8]])

- when we want vertical concatentaion i.e. concatenation along column:

In [66]:
# using np.concatenate() method:
np.concatenate((a,b),axis=0)

array([[1, 2],
       [3, 4],
       [5, 6],
       [7, 8]])

In [69]:
# using np.vstack() method:
np.vstack((a,b))

array([[1, 2],
       [3, 4],
       [5, 6],
       [7, 8]])

- when we want horizontal concatentaion i.e. concatenation along row:

In [70]:
# using np.concatenate() method:
np.concatenate((a,b),axis=1)

array([[1, 2, 5, 6],
       [3, 4, 7, 8]])

In [71]:
# using np.hstack() method:
np.hstack((a,b))

array([[1, 2, 5, 6],
       [3, 4, 7, 8]])

### Note:
- In Pandas:
  - 1-D array is called Series
  - 2-D array is called Data frame.
- **Generally**
  - Whenever we have 1-D array related stuff we go for NumPy
  - Whenever we have 2-D array related stuff we go for Pandas (Data frame)